### ISSUE TITLE
Inconsistent TX processing

### ISSUE THREAD

**Issue by worlddeleteRin** [roman-khimov/neo-go#2] opened 2023-03-09 19:38 UTC
### Problem:
**[Testnet]** Inconsistent TX processing between neo-go and neo-c# nodes on

Tx hash example:
`0xc9bcd2e27847d95a73de652759d9eeeaeee8499292d06b42f495136f421a3f56`

### JSON-RPC request:
```json
{
    "params": ["0xc9bcd2e27847d95a73de652759d9eeeaeee8499292d06b42f495136f421a3f56"],
    "jsonrpc": "2.0",
    "id": 123,
    "method": "getapplicationlog"
}
```

### Neo-c# result:
```json
{
    "jsonrpc": "2.0",
    "id": 123,
    "result": {
        "txid": "0xc9bcd2e27847d95a73de652759d9eeeaeee8499292d06b42f495136f421a3f56",
        "executions": [
            {
                "trigger": "Application",
                "vmstate": "HALT",
                "exception": null,
                "gasconsumed": "113138851",
                "stack":  []
                // etc.
            }
        ]
    }
}
```
### Neo-go result:
```json
{
    "id": 123,
    "jsonrpc": "2.0",
    "result": {
        "txid": "0xc9bcd2e27847d95a73de652759d9eeeaeee8499292d06b42f495136f421a3f56",
        "executions": [
            {
                "trigger": "Application",
                "vmstate": "FAULT",
                "gasconsumed": "1915872",
                "stack": [],
                "notifications": [],
                "exception": "at instruction 428 (THROW): unhandled exception: \"ListTokenInternal - invalid owner\""
            }
        ]
    }
}
```

**Comment by AnnaShaleva** [comment] 2023-03-10 12:23
@worlddeleteRin, thank you for submitting the issue.

I've made an investigation and found the states diff at block 1670095 of the current testnet (it happens earlier than your issue). The state diff is connected with failed contract `b531a2ec582c2806023c63cba7c3e752a459afaa` update (the same contract is called in your case). See the https://github.com/neo-project/neo/issues/2848, it's likely to be the reason of states diff in your case as far.

For now, we are waiting the https://github.com/neo-project/neo/issues/2848 to be resolved. After that (if it's not the cause of your issue) I'll continue investigation.

**Comment by roman-khimov** [comment] 2023-03-14 10:09
I'll close this one, nspcc-dev is back, but unfortunately GitHub doesn't allow transferring issues between private and org repositories. We have neo-project/neo#2848 to track the main problem and it seems like no NeoGo modifications are not necessary here. If there'll be something to do based on that we'll create a new issue/PR in nspcc-dev/neo-go.

**Closed as completed by roman-khimov** 2023-03-14 10:09 UTC
